name: Quran API Server Status Check

on:
  push:
    branches:
      - main
  schedule:
      - cron: "0 */5 * * *" # Runs every 5 hours

jobs:
  check-server-status:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Send POST request to Quran API
      id: post-request
      run: |
        response=$(curl -s -X POST https://quran.x10.mx/ \
          -H "Content-Type: application/json" \
          -d '{"action": "getVerseDetails", "chapter": 1, "verse": 1, "edition_id": 20}')
        echo "API_RESPONSE=$response" >> $GITHUB_ENV

    - name: Parse API response
      id: parse-response
      run: |
        status=$(echo "$API_RESPONSE" | jq -r .status)
        if [ "$status" == "success" ]; then
          echo "SERVER_STATUS=up" >> $GITHUB_ENV
        else
          echo "SERVER_STATUS=down" >> $GITHUB_ENV
        fi

    - name: Update README.md
      run: |
        status_text="**Server Status:** "
        if [ "$SERVER_STATUS" == "up" ]; then
          status_text+="✅ **| Up and Running... hooray!**"
        else
          status_text+="❌ **| Down... 🥺**"
        fi
    
        # Escape special characters in the string before passing to sed
        escaped_status_text=$(echo "$status_text" | sed 's/[&/\]/\\&/g')
    
        # Update or append server status in README.md
        if grep -q "^**Server Status:**" README.md; then
          sed -i "s|^**Server Status:**.*|$escaped_status_text|" README.md
        else
          echo -e "\n$escaped_status_text" >> README.md
        fi



    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "79928743+ktauchathuranga@users.noreply.github.com"

        git add README.md
        git commit -m "Update server status"
        git push
